name: Build and Pack FirmaXadesNet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore packages (por si acaso)
        run: nuget restore FirmaXadesNet.sln

      - name: Build solution (Release)
        run: msbuild FirmaXadesNet.sln /p:Configuration=Release

      - name: Create NuGet package
        run: nuget pack FirmaXadesNet.nuspec -OutputDirectory out

      - name: Upload nupkg as artifact
        uses: actions/upload-artifact@v4
        with:
          name: FirmaXadesNet-nupkg
          path: out/*.nupkg
